[2025-04-20 16:29:38] [::1] [User: 3] RTK API account creation failed | Context: {"registration_id":71,"api_error":"JSON parse error: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 66] (through reference chain: cn.huace.cgbas.broadcast.dto.form.BroadcastUserForm[\"customerCompany\"])","api_response":{"code":"Internal Server Error","msg":"JSON parse error: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 66] (through reference chain: cn.huace.cgbas.broadcast.dto.form.BroadcastUserForm[\"customerCompany\"])","data":null},"request_data":{"name":"VnNguyn","userPwd":"******","startTime":1745166576000,"endTime":1745771376000,"enabled":1,"numOnline":1,"customerName":"Đỗ Văn Nguyên","customerPhone":"0981190561","customerBizType":1}}
[2025-04-20 16:29:38] [::1] [User: 3] General error during trial activation | Context: {"registration_id":71,"error":"Không thể tạo tài khoản RTK: JSON parse error: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 66] (through reference chain: cn.huace.cgbas.broadcast.dto.form.BroadcastUserForm[\"customerCompany\"])","trace":"#0 {main}"}
[2025-04-20 16:31:08] [::1] [User: 3] Trial activation successful | Context: {"registration_id":72,"account_id":"RTK_72_1745166668","username":"VnNguyn"}
[2025-04-20 16:33:12] [::1] [User: 3] Trial activation successful | Context: {"registration_id":73,"account_id":"RTK_73_1745166792","username":"VnNguyn1"}
[2025-04-20 16:33:37] [::1] [User: 3] Trial activation successful | Context: {"registration_id":74,"account_id":"RTK_74_1745166817","username":"VnNguyn2"}
[2025-04-20 16:39:19] [::1] [User: 3] Trial activation successful | Context: {"registration_id":75,"account_id":"RTK_75_1745167159","username":"VnNguyn3"}
[2025-04-21 06:59:35] [::1] [User: 10] Trial activation successful | Context: {"registration_id":81,"account_id":"RTK_81_1745218775","username":"nagmailcom"}
[2025-04-21 07:04:07] [::1] [User: 11] Trial activation successful | Context: {"registration_id":82,"account_id":"RTK_82_1745219047","username":"new2gmailcom"}
[2025-04-21 08:02:59] [::1] [User: 12] Trial activation successful | Context: {"registration_id":83,"account_id":"RTK_83_1745222579","username":"new5gmailcom"}
[2025-04-21 08:43:57] [::1] [User: 13] Trial activation successful | Context: {"registration_id":84,"account_id":"RTK_84_1745225037","username":"Zia"}
[2025-04-21 14:57:46] [::1] [User: 14] Trial activation successful | Context: {"registration_id":87,"account_id":"RTK_87_1745247466","username":"new7gmailcom"}
[2025-04-22 09:39:46] [::1] [User: 15] Trial activation successful | Context: {"registration_id":90,"account_id":"RTK_90_1745314786","username":"Duy"}
[2025-04-22 09:47:56] [::1] [User: 16] RTK API account creation failed | Context: {"registration_id":91,"api_error":"Missing required field: locationId","api_response":null,"request_data":{"name":"cgmailcom","userPwd":"******","startTime":1745315275000,"endTime":1745920075000,"enabled":1,"numOnline":1,"customerName":"c@gmail.com","customerPhone":"0981190544","customerBizType":1,"customerCompany":"","casterIds":[],"regionIds":[],"mountIds":[]}}
[2025-04-22 09:47:56] [::1] [User: 16] General error during trial activation | Context: {"registration_id":91,"error":"Không thể tạo tài khoản RTK: Missing required field: locationId","trace":"#0 {main}"}
[2025-04-22 09:47:58] [::1] [User: 16] RTK API account creation failed | Context: {"registration_id":91,"api_error":"Missing required field: locationId","api_response":null,"request_data":{"name":"cgmailcom","userPwd":"******","startTime":1745315275000,"endTime":1745920075000,"enabled":1,"numOnline":1,"customerName":"c@gmail.com","customerPhone":"0981190544","customerBizType":1,"customerCompany":"","casterIds":[],"regionIds":[],"mountIds":[]}}
[2025-04-22 09:47:58] [::1] [User: 16] General error during trial activation | Context: {"registration_id":91,"error":"Không thể tạo tài khoản RTK: Missing required field: locationId","trace":"#0 {main}"}
[2025-04-22 09:47:58] [::1] [User: 16] RTK API account creation failed | Context: {"registration_id":91,"api_error":"Missing required field: locationId","api_response":null,"request_data":{"name":"cgmailcom","userPwd":"******","startTime":1745315275000,"endTime":1745920075000,"enabled":1,"numOnline":1,"customerName":"c@gmail.com","customerPhone":"0981190544","customerBizType":1,"customerCompany":"","casterIds":[],"regionIds":[],"mountIds":[]}}
[2025-04-22 09:47:58] [::1] [User: 16] General error during trial activation | Context: {"registration_id":91,"error":"Không thể tạo tài khoản RTK: Missing required field: locationId","trace":"#0 {main}"}
[2025-04-22 09:51:52] [::1] [User: 17] RTK API account creation failed | Context: {"registration_id":92,"api_error":"No mount points found for location ID: 15","api_response":null,"request_data":{"name":"aacccgmailcom","userPwd":"******","startTime":1745315511000,"endTime":1745920311000,"locationId":15,"enabled":1,"numOnline":1,"customerName":"aaccc@gmail.com","customerPhone":"0981190533","customerBizType":1,"customerCompany":"","casterIds":[],"regionIds":[],"mountIds":[]}}
[2025-04-22 09:51:52] [::1] [User: 17] General error during trial activation | Context: {"registration_id":92,"error":"Không thể tạo tài khoản RTK: No mount points found for location ID: 15","trace":"#0 {main}"}
[2025-04-22 09:51:53] [::1] [User: 17] RTK API account creation failed | Context: {"registration_id":92,"api_error":"No mount points found for location ID: 15","api_response":null,"request_data":{"name":"aacccgmailcom","userPwd":"******","startTime":1745315511000,"endTime":1745920311000,"locationId":15,"enabled":1,"numOnline":1,"customerName":"aaccc@gmail.com","customerPhone":"0981190533","customerBizType":1,"customerCompany":"","casterIds":[],"regionIds":[],"mountIds":[]}}
[2025-04-22 09:51:53] [::1] [User: 17] General error during trial activation | Context: {"registration_id":92,"error":"Không thể tạo tài khoản RTK: No mount points found for location ID: 15","trace":"#0 {main}"}
[2025-04-22 09:51:53] [::1] [User: 17] RTK API account creation failed | Context: {"registration_id":92,"api_error":"No mount points found for location ID: 15","api_response":null,"request_data":{"name":"aacccgmailcom","userPwd":"******","startTime":1745315511000,"endTime":1745920311000,"locationId":15,"enabled":1,"numOnline":1,"customerName":"aaccc@gmail.com","customerPhone":"0981190533","customerBizType":1,"customerCompany":"","casterIds":[],"regionIds":[],"mountIds":[]}}
[2025-04-22 09:51:53] [::1] [User: 17] General error during trial activation | Context: {"registration_id":92,"error":"Không thể tạo tài khoản RTK: No mount points found for location ID: 15","trace":"#0 {main}"}
[2025-04-22 09:52:57] [::1] [User: 18] RTK API account creation failed | Context: {"registration_id":93,"api_error":"No mount points found for location ID: 63","api_response":null,"request_data":{"name":"aaccccccgmailcom","userPwd":"******","startTime":1745315575000,"endTime":1745920375000,"locationId":63,"enabled":1,"numOnline":1,"customerName":"aacccccc@gmail.com","customerPhone":"0481190564","customerBizType":1,"customerCompany":"","casterIds":[],"regionIds":[],"mountIds":[]}}
[2025-04-22 09:52:57] [::1] [User: 18] General error during trial activation | Context: {"registration_id":93,"error":"Không thể tạo tài khoản RTK: No mount points found for location ID: 63","trace":"#0 {main}"}
[2025-04-22 10:17:50] [::1] [User: 19] Trial activation successful | Context: {"registration_id":94,"account_id":"RTK_94_1745317070","username":"aaccccddccgmailcom"}
[2025-04-22 10:27:00] [::1] [User: 20] Mount points for location | Context: {"location_id":63,"mount_points":["MP_YB_01","MP_YB_02","MP_YB_03","MP_YB_04","MP_YB_05","MP_YB_06","MP_YB_07","MP_YB_08"]}
[2025-04-22 10:27:00] [::1] [User: 20] RTK API account creation failed | Context: {"registration_id":95,"api_error":"JSON parse error: Cannot deserialize value of type `java.lang.Long` from String \"MP_YB_01\": not a valid Long value; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Long` from String \"MP_YB_01\": not a valid Long value\n at [Source: (PushbackInputStream); line: 1, column: 111] (through reference chain: cn.huace.cgbas.broadcast.dto.form.BroadcastUserForm[\"mountIds\"]->java.util.ArrayList[0])","api_response":{"code":"Internal Server Error","msg":"JSON parse error: Cannot deserialize value of type `java.lang.Long` from String \"MP_YB_01\": not a valid Long value; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Long` from String \"MP_YB_01\": not a valid Long value\n at [Source: (PushbackInputStream); line: 1, column: 111] (through reference chain: cn.huace.cgbas.broadcast.dto.form.BroadcastUserForm[\"mountIds\"]->java.util.ArrayList[0])","data":null},"request_data":{"name":"aarrrgmailcom","userPwd":"******","startTime":1745317619000,"endTime":1745922419000,"locationId":63,"enabled":1,"numOnline":1,"customerName":"aarrr@gmail.com","customerPhone":"0981190223","customerBizType":1,"customerCompany":"","casterIds":[],"regionIds":[],"mountIds":["MP_YB_01","MP_YB_02","MP_YB_03","MP_YB_04","MP_YB_05","MP_YB_06","MP_YB_07","MP_YB_08"]}}
[2025-04-22 10:27:00] [::1] [User: 20] General error during trial activation | Context: {"registration_id":95,"error":"Không thể tạo tài khoản RTK: JSON parse error: Cannot deserialize value of type `java.lang.Long` from String \"MP_YB_01\": not a valid Long value; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Long` from String \"MP_YB_01\": not a valid Long value\n at [Source: (PushbackInputStream); line: 1, column: 111] (through reference chain: cn.huace.cgbas.broadcast.dto.form.BroadcastUserForm[\"mountIds\"]->java.util.ArrayList[0])","trace":"#0 {main}"}
[2025-04-22 10:42:02] [::1] [User: 21] Mount points for location (numeric) | Context: {"location_id":63,"mount_points":[44,45,46,47,48,49,60,64]}
[2025-04-22 10:42:02] [::1] [User: 21] Trial activation successful | Context: {"registration_id":96,"account_id":"RTK_96_1745318522","username":"new9999gmailcom"}
[2025-04-24 16:02:20] [::1] [User: 1] Mount points for location (numeric) | Context: {"location_id":63,"mount_points":[44,45,46,47,48,49,60,64]}
[2025-04-24 16:02:20] [::1] [User: 1] Trial activation successful | Context: {"registration_id":1,"account_id":"RTK_1_1745510540","username":"CngtySao"}
[2025-04-25 11:02:46] [::1] [User: 2] Mount points for location (numeric) | Context: {"location_id":63,"mount_points":[44,45,46,47,48,49,60,64]}
[2025-04-25 11:02:46] [::1] [User: 2] Trial activation successful | Context: {"registration_id":2,"account_id":"RTK_2_1745578966","username":"DimMcChu"}
[2025-04-25 11:08:48] [::1] [User: 87] Mount points for location (numeric) | Context: {"location_id":63,"mount_points":[44,45,46,47,48,49,60,64]}
[2025-04-25 11:08:48] [::1] [User: 87] Trial activation successful | Context: {"registration_id":3,"account_id":"RTK_3_1745579328","username":"test3"}
[2025-04-25 15:10:07] [::1] [User: 1] Mount points for location (string) | Context: {"location_id":63,"mount_points":["YBI_TPYenBai","YBI_NghiaLo","YBI_LucYen","YBI_TramTau","YBI_VanYen","YBI_MuCangChai","YenBai","YBI_XuanAI"]}
[2025-04-25 15:10:07] [::1] [User: 1] RTK API account creation failed | Context: {"registration_id":5,"api_error":"JSON parse error: Cannot deserialize value of type `java.lang.Long` from String \"YBI_TPYenBai\": not a valid Long value; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Long` from String \"YBI_TPYenBai\": not a valid Long value\n at [Source: (PushbackInputStream); line: 1, column: 111] (through reference chain: cn.huace.cgbas.broadcast.dto.form.BroadcastUserForm[\"mountIds\"]->java.util.ArrayList[0])","api_response":{"code":"Internal Server Error","msg":"JSON parse error: Cannot deserialize value of type `java.lang.Long` from String \"YBI_TPYenBai\": not a valid Long value; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Long` from String \"YBI_TPYenBai\": not a valid Long value\n at [Source: (PushbackInputStream); line: 1, column: 111] (through reference chain: cn.huace.cgbas.broadcast.dto.form.BroadcastUserForm[\"mountIds\"]->java.util.ArrayList[0])","data":null},"request_data":{"name":"TRIAL_YBI001","userPwd":"******","startTime":1745593806000,"endTime":1746198606000,"locationId":63,"enabled":1,"numOnline":1,"customerName":"Công ty Sao đỏ","customerPhone":"0868458693","customerBizType":1,"customerCompany":"","casterIds":[],"regionIds":[],"mountIds":["YBI_TPYenBai","YBI_NghiaLo","YBI_LucYen","YBI_TramTau","YBI_VanYen","YBI_MuCangChai","YenBai","YBI_XuanAI"]}}
[2025-04-25 15:10:07] [::1] [User: 1] General error during trial activation | Context: {"registration_id":5,"error":"Không thể tạo tài khoản RTK: JSON parse error: Cannot deserialize value of type `java.lang.Long` from String \"YBI_TPYenBai\": not a valid Long value; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Long` from String \"YBI_TPYenBai\": not a valid Long value\n at [Source: (PushbackInputStream); line: 1, column: 111] (through reference chain: cn.huace.cgbas.broadcast.dto.form.BroadcastUserForm[\"mountIds\"]->java.util.ArrayList[0])","trace":"#0 {main}"}
[2025-04-25 15:11:27] [::1] [User: 1] Mount points for location (string) | Context: {"location_id":63,"mount_points":[44,45,46,47,48,49,60,64]}
[2025-04-25 15:11:27] [::1] [User: 1] Trial activation successful | Context: {"registration_id":6,"account_id":"RTK_6_1745593887","username":"TRIAL_YBI001"}
[29-Apr-2025 10:15:39 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:15:39 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:15:40 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:15:40 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:15:40 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:15:40 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:15:42 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:15:42 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:15:42 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:15:42 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:15:42 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:15:42 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:15:42 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:15:42 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:15:42 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:15:43 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:15:43 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:15:43 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:15:43 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:15:43 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:15:43 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:26:52 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:26:52 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:26:56 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:26:56 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:26:56 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:26:56 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:27:01 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:27:01 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:27:01 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:27:01 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:27:01 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:27:01 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:27:01 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:27:01 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:27:01 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:27:05 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:27:05 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:27:05 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:27:05 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:27:05 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:27:05 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:27:49 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:27:49 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:27:49 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:28:10 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:28:10 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:28:12 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:28:12 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:28:12 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:28:12 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:28:18 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:28:18 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:28:18 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:28:18 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:28:18 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:28:18 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:28:18 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:28:18 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:28:18 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:28:23 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:28:23 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:28:23 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:28:28 UTC] Project root path: C:\laragon\www\rtk_web
[29-Apr-2025 10:28:28 UTC] Upload directory: C:\laragon\www\rtk_web/public/uploads/payment_proofs/
[29-Apr-2025 10:28:28 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:28:28 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:28:28 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:28:29 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:28:29 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:28:29 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:28:38 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:28:38 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:28:38 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:28:46 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:28:46 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:28:46 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:28:51 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:28:51 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:28:51 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:28:51 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:28:51 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:28:51 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:29:02 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:29:02 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:29:02 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:29:03 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:29:03 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:29:03 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:29:06 UTC] PHP Error [8192]: Constant FILTER_SANITIZE_STRING is deprecated in C:\laragon\www\rtk_web\public\pages\invoice\request_export_invoice.php on line 21
[29-Apr-2025 10:29:38 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:29:38 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:29:38 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:29:39 UTC] PHP Error [8192]: Constant FILTER_SANITIZE_STRING is deprecated in C:\laragon\www\rtk_web\public\pages\invoice\request_export_invoice.php on line 21
[29-Apr-2025 10:30:49 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:30:49 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:30:49 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:30:52 UTC] PHP Error [8192]: Constant FILTER_SANITIZE_STRING is deprecated in C:\laragon\www\rtk_web\public\pages\invoice\request_export_invoice.php on line 21
[29-Apr-2025 10:30:54 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:30:54 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:30:54 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:30:55 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:30:55 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:30:55 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:30:57 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:30:57 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:30:57 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:30:59 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:30:59 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:30:59 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:31:00 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:31:00 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:31:00 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:31:03 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:31:03 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:31:03 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:31:08 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:31:08 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:31:08 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:31:10 UTC] PHP Error [8192]: Constant FILTER_SANITIZE_STRING is deprecated in C:\laragon\www\rtk_web\public\pages\invoice\request_export_invoice.php on line 21
[29-Apr-2025 10:31:12 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:31:12 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:31:12 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:31:43 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:31:43 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:31:43 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:31:45 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:31:45 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:31:45 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:31:46 UTC] PHP Error [8192]: Constant FILTER_SANITIZE_STRING is deprecated in C:\laragon\www\rtk_web\public\pages\invoice\request_export_invoice.php on line 21
[29-Apr-2025 10:32:03 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:32:03 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:32:03 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:32:04 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:32:04 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:32:04 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:32:10 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:32:10 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:32:10 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:32:10 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:32:10 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:32:10 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:32:12 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:32:12 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:32:12 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:32:25 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:32:25 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:32:25 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:32:28 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:32:28 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:32:28 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:32:32 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:32:32 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:32:32 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:32:36 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:32:36 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:32:36 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:32:46 UTC] PHP Error [8192]: Constant FILTER_SANITIZE_STRING is deprecated in C:\laragon\www\rtk_web\public\pages\invoice\request_export_invoice.php on line 21
[29-Apr-2025 10:33:37 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:33:37 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:33:37 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:33:39 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:33:39 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:33:39 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:33:40 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:33:40 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:33:40 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:33:42 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:33:42 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:33:42 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:33:44 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:33:44 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:33:44 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:33:44 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:33:44 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:33:44 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:33:44 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:33:44 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:33:44 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:33:49 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:33:49 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:33:49 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:33:51 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:33:51 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:33:51 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:33:52 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:33:52 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:33:52 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:33:54 UTC] PHP Error [8192]: Constant FILTER_SANITIZE_STRING is deprecated in C:\laragon\www\rtk_web\public\pages\invoice\request_export_invoice.php on line 21
[29-Apr-2025 10:33:56 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:33:56 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:33:56 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:34:40 UTC] PHP Error [8192]: Constant FILTER_SANITIZE_STRING is deprecated in C:\laragon\www\rtk_web\public\pages\invoice\request_export_invoice.php on line 21
[29-Apr-2025 10:35:04 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:35:04 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:35:04 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:38:13 UTC] PHP Error [8192]: Constant FILTER_SANITIZE_STRING is deprecated in C:\laragon\www\rtk_web\public\pages\invoice\request_export_invoice.php on line 21
[29-Apr-2025 10:38:15 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:38:15 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:38:15 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:38:18 UTC] PHP Error [8192]: Constant FILTER_SANITIZE_STRING is deprecated in C:\laragon\www\rtk_web\public\pages\invoice\request_export_invoice.php on line 21
[29-Apr-2025 10:38:21 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:38:21 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:38:21 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:38:23 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:38:23 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:38:23 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:38:58 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:38:58 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:38:59 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:38:59 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:38:59 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:39:00 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:39:00 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:39:00 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:39:01 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:39:01 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:39:01 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:39:03 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:39:03 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:39:03 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:39:03 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:39:03 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:39:03 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:39:08 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:39:08 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:39:08 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:39:40 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:39:40 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:39:40 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:39:41 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:39:41 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:39:41 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:39:43 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:39:43 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:39:43 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:39:43 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:39:43 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:39:43 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:39:47 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:39:47 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:39:47 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:39:49 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:39:49 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:39:49 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:39:51 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:39:51 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:39:51 UTC] [Database Connect] Connection to database 'sa_database' successful.
[29-Apr-2025 10:40:15 UTC] Database init: Using database 'sa_database' on host '127.0.0.1'
[29-Apr-2025 10:40:15 UTC] [Database GetConnection] No active connection found. Attempting to connect...
[29-Apr-2025 10:40:15 UTC] [Database Connect] Connection to database 'sa_database' successful.
